// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALqXGI9g7EqK3O229zrkk3HzwaF7wP-Cc',
    appId: '1:576678750420:android:8efa3691bf2d8ef679b341',
    messagingSenderId: '576678750420',
    projectId: 'first-d3bb6',
    databaseURL: 'https://first-d3bb6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'first-d3bb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOQ5hMZZKnhMHaPsYAZkfJTzUZJ4BB10E',
    appId: '1:576678750420:ios:e54fdc2d9f62023379b341',
    messagingSenderId: '576678750420',
    projectId: 'first-d3bb6',
    databaseURL: 'https://first-d3bb6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'first-d3bb6.appspot.com',
    iosClientId: '576678750420-7d5ack1u0evhcfa2afgm5tqks0arq5df.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );
}
